version: 0.1.0   

name: Deploy a Node application to Azure App service
description: A GitHub Stack to develop, preview, and deploy an Express(Node.js) website to Azure App service in seconds.

branding:
  icon: 'cloud'
  color: 'red'

inputs:

  - name: AZURE_APP_SERVICE_NAME
    description: Enter the name of the Azure App Service
    is-secret: false
    required: true
  
configs:
   repo-metadata:
      parameters:
        description: 'A Nodejs website deployed in Azure App Service'
        topics:
        - nodejs
        - expressjs
        - azure
        
   branches:
    - name: main
      parameters: 
        allow-force-pushes: false
        required-pull-request-reviews:
          dismiss-stale-reviews: true
    
github-apps:
- slug: azure-oidc

init:
 uses: "stack-init.yaml"
