name: "deploy"
on:
  push:
    branches: [ main ]

permissions:
   id-token: write
   contents: write

jobs:
  deploy: 
    runs-on: ubuntu-latest
    name: "Deploy nodejs app to GCP app engine"
    environment:
       name: development
       url: ${{ steps.get-url.outputs.your_site }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "package.json"
      
      - name: use node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: true
          registry-url: https://registry.npmjs.org/
      
      - name: npm install, build, and test
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          npm install
          npm run build

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/39305491180/locations/global/workloadIdentityPools/node-workload-identity/providers/gh-app-engine'
          service_account: 'gcp-user@third-wharf-342109.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
